// frontend/react/src/components/Footer/Footer.tsx
import React from "react";
import { paymentWaysTitle } from "../../constants/global";
import PaymentImage from "../../assets/images/credit_cards_logos.png";
import "./styles.scss";

export const Footer:React.FC<{descriptionTxt:string}> = ({descriptionTxt}) => {
  return (
    <div className="rodape">
      <div className="fx2">
        <div className="md">
          <ul className="colTb md100pc">
            <li>
              <span>
                2021 - {(new Date()).getFullYear()} • {descriptionTxt}
              </span>
            </li>
            <li>
              <img
                src={PaymentImage}
                width="200"
                alt={paymentWaysTitle}
                title={paymentWaysTitle}
              />
            </li>
          </ul>
        </div>
      </div>
    </div>
  );
};

// frontend/angular/src/app/components/footer/footer.component.ts
import { Component, Input } from '@angular/core';
import { Isettings } from 'src/app/models/interfaces/settings.interface';

@Component({
  selector: 'app-footer',
  templateUrl: './footer.component.html',
  styleUrls: ['./footer.component.scss'],
})
export class FooterComponent {
  @Input() settings: Isettings | undefined;
  public currentYear: number = new Date().getFullYear();
  public PaymentImage: string = 'assets/images/credit_cards_logos.png';
}

<div class="rodape">
  <div class="fx2">
    <div class="md">
      <ul class="colTb md100pc">
        <li>
          <span>
            2021 - {{ currentYear }} • {{ settings?.textoRodape }}
          </span>
        </li>
        <li>
          <img
            src={{PaymentImage}}
            width="200"
            alt={paymentWaysTitle}
            title={paymentWaysTitle}
          />
        </li>
      </ul>
    </div>
  </div>
</div>
