// frontend/angular/src/app/pages/home/home.component.ts
import { Component } from '@angular/core';
import { SERVICES_TITLE, CATALOG_TITLE, ECOMMERCE_TITLE } from 'src/app/constants/constants';

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.scss']
})
export class HomeComponent {
  serviceImage = 'assets/images/servicos.jpg';
  catalogImage = 'assets/images/catalogo.jpg';
  ecommerceImage = 'assets/images/loja.jpg';

  servicesTitle = SERVICES_TITLE;
  catalogTitle = CATALOG_TITLE;
  ecommerceTitle = ECOMMERCE_TITLE;
}

<div class="component-home">
  <div class="bloco-item-home" [routerLink]="['/servicos']">
      <div class="img-block">
        <img src={{serviceImage}} alt="serviços" />
      </div>
      <div class="bloco-descricao">
        <span>{{servicesTitle}}</span>
      </div>
  </div>

  <div class="bloco-item-home" [routerLink]="['/catalogo']">
      <div class="img-block">
        <img src={{catalogImage}} alt="Catálogo" />
      </div>
      <div class="bloco-descricao">
        <span>{{catalogTitle}}</span>
      </div>
  </div>

  <div class="bloco-item-home" [routerLink]="['/loja']">
      <div class="img-block">
        <img src={{ecommerceImage}} alt="Loja Virtual Online" />
      </div>
      <div class="bloco-descricao">
        <span>{{ecommerceTitle}}</span>
      </div>
  </div>
</div>

// frontend/react/src/pages/Home/index.tsx
import { Link } from "react-router-dom";
import { TemplateDefault } from "../../components/Templates/TemplateDefault";
import { catalogTitle, ecommerceTitle, homeTitle, servicesTitle } from "../../constants/global";
import "./styles.scss";
import serviceImage from "../../assets/images/servicos.jpg";
import catalogoImage from "../../assets/images/catalogo.jpg";
import lojaImage from "../../assets/images/loja.jpg";

export const Home: React.FC<{ isLoading: boolean }> = ({ isLoading }) => {
  return (
    <TemplateDefault title={homeTitle} isLoading={isLoading}>
      <div className="component-home">
        <div className="bloco-item-home">
          <Link to="/servicos">
            <div className="img-block">
              <img src={serviceImage} alt="serviços" />
            </div>
            <div className="bloco-descricao">
              <span>{servicesTitle}</span>
            </div>
          </Link>
        </div>

        <div className="bloco-item-home">
          <Link to="/catalogo">
            <div className="img-block">
              <img src={catalogoImage} alt="Catálogo" />
            </div>
            <div className="bloco-descricao">
              <span>{catalogTitle}</span>
            </div>
          </Link>
        </div>

        <div className="bloco-item-home">
          <Link to="/loja">
            <div className="img-block">
              <img src={lojaImage} alt="Loja Virtual Online" />
            </div>
            <div className="bloco-descricao">
              <span>{ecommerceTitle}</span>
            </div>
          </Link>
        </div>
      </div>
    </TemplateDefault>
  );
};
