// frontend/angular/src/app/components/content/content/content.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-content',
  templateUrl: './content.component.html',
  styleUrls: ['./content.component.scss'],
})
export class ContentComponent {
  @Input() htmlContent: string | undefined;
  @Input() titleText: string | undefined;
  @Input() loading = false;
}

<div class="quadro">
  <div class="conteudos">
    <div class="wrapConteudo">
      <div id="areaConteudos" class="mobile-content">
        <div class="home-conteudos">
          <router-outlet *ngIf="!htmlContent"></router-outlet>
        </div>
      </div>
    </div>
    <app-spinner></app-spinner>
  </div>
</div>

// frontend/react/src/components/Content/Content.tsx
//Content.tsx
import { ReactNode } from "react";
import "./styles.scss";
import { LoadingSpinner } from "../Loading/Spinner";

type ContentProps = {
  children?: ReactNode;
  content?: string;
  contentId?: number;
  isHTML?: boolean;
  isLoading: boolean;
};

export const Content = ({
  children,
  isHTML,
  content,
  contentId,
  isLoading,
}: ContentProps) => {
  return (
    <div className="quadro">
      <div className="conteudos">
        <div className="wrapConteudo">
          <div id="areaConteudos" className="mobile-content">
            <div className="home-conteudos">
              {isHTML && content !== undefined ? (
                <>
                  <div dangerouslySetInnerHTML={{ __html: content }} />
                  <LoadingSpinner isLoading={isLoading} />
                </>
              ) : (
                children
              )}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};
